p_0:
  constraint: increasing([A,B,C])
  predicate: p
  streams:
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
    Z:
      direction: input
      name: z
  substitutions:
    A: X
    B: Y
    C: Z
p_1:
  constraint: A < B
  predicate: q
  streams:
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
  substitutions:
    A: X
    B: Y
p_2:
  constraint: A < B
  predicate: q
  streams:
    X:
      direction: input
      name: x
    Z:
      direction: input
      name: z
  substitutions:
    A: X
    B: Z
