states:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
initial: 0
accepting:
- 0
- 6
- 11
- 12
9:
  2: p_1
  3: ~p_0 & ~p_1
  14: p_0 & ~p_1
1:
  2: ~p_1
  3: p_1 & ~p_0
  14: p_0 & p_1
7:
  2: ~p_1
  7: p_0 & p_1
  8: p_1 & ~p_0
10:
  1: p_0
  4: ~p_0
4:
  2: ~p_1
  6: p_1 & ~p_0
  9: p_0 & p_1
8:
  1: p_0 & p_1
  2: ~p_1
  4: p_1 & ~p_0
3:
  1: p_0 & ~p_1
  2: p_1
  4: ~p_0 & ~p_1
11:
  6: ~p_0
  9: p_0
6:
  2: p_1
  6: ~p_0 & ~p_1
  9: p_0 & ~p_1
12:
  11: ~p_0
  13: p_0
14:
  2: p_1
  7: p_0 & ~p_1
  8: ~p_0 & ~p_1
13:
  3: ~p_0
  14: p_0
15:
  5: p_0
  10: ~p_0
5:
  7: p_0
  8: ~p_0
0:
  12: ~p_0
  15: p_0
2:
  2: 'True'
