states:
- 0
- 1
- 2
- 3
- 4
initial: 0
accepting:
- 4
2:
  1: ~p_2
  2: p_1 & p_2 & ~p_0
  3: p_2 & ~p_0 & ~p_1
  4: p_0 & p_2
3:
  1: p_2
  2: p_1 & ~p_0 & ~p_2
  3: ~p_0 & ~p_1 & ~p_2
  4: p_0 & ~p_2
1:
  1: 'True'
4:
  4: 'True'
0:
  2: p_1 & ~p_0
  3: ~p_0 & ~p_1
  4: p_0
