p_0:
  constraint: (A + B) mod 10 = C
  predicate: p
  streams:
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
    Z:
      direction: output
      name: z
  substitutions:
    A: X
    B: Y
    C: Z
p_1:
  constraint: (A - B + 10) mod 10 = C
  predicate: q
  streams:
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
    Z:
      direction: output
      name: z
  substitutions:
    A: X
    B: Y
    C: Z
p_2:
  constraint: (A * B) mod 10 = C
  predicate: r
  streams:
    X:
      direction: input
      name: x
    Y:
      direction: input
      name: y
    Z:
      direction: output
      name: z
  substitutions:
    A: X
    B: Y
    C: Z
p_3:
  constraint: A div B = C
  predicate: s
  streams:
    W:
      direction: input
      name: y
    X:
      direction: input
      name: x
    Z:
      direction: output
      name: z
  substitutions:
    A: X
    B: W
    C: Z
